version: '3'
services:
  mysql:
    build: ./docker/db/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      TZ: "Asia/Tokyo"
    restart: always
  app:
    image: nginx:1.13.5-alpine
    ports:
      - "8080:80"
    links:
      - mysql
    volumes:
      - ./src:/var/www/html
    stdin_open: true
    tty: true
