version: '3'

services:
  spring-db:
    container_name: spring-db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "root"
      MYSQL_DATABASE: "testdb"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
